code/FileUploadSpike/Models/AjaxFormPostResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FileUploadSpike.Models
{
    public class AjaxFormPostResponse
    {
        public bool Success { get; set; }

        public string Message { get; set; }

        public string RedirectUrl { get; set; }

        public object AdditionalData { get; set; }
    }
}

code/FileUploadSpike/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FileUploadSpike.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return this.View();
        }
    }
}

code/FileUploadSpike/Controllers/UploadController.cs
using FileUploadSpike.ActionFilters;
using FileUploadSpike.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FileUploadSpike.Controllers
{
    public class UploadController : Controller
    {
        #region Standard HTTP upload

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file1, HttpPostedFileBase file2, string other)
        {
            return View(new
            {
                File1Data = file1 != null ? string.Join(" : ", new object[] { file1.ContentLength.ToString() + " bytes", file1.ContentType, file1.FileName }) : "No file",
                File2Data = file2 != null ? string.Join(" : ", new object[] { file2.ContentLength.ToString() + " bytes", file2.ContentType, file2.FileName }) : "No file",
            });
        }

        #endregion

        #region Upload with FormData

        public ActionResult FormData()
        {
            return this.View();
        }

        [HttpPost, FilterClientDisconnectedRequests]
        public JsonResult FormData(HttpPostedFileBase file1, string other)
        {
            return Json(new AjaxFormPostResponse
            {
                Success = true,
                Message = this.GetFileData(file1)
            });
        }

        #endregion

        #region Upload to missing endpoint

        [HttpGet]
        public ActionResult FormDataServerError()
        {
            return this.View("FormData");
        }

        #endregion

        #region Upload to endpoint with error response

        public ActionResult FormDataServerTrappedError()
        {
            return this.View("FormData");
        }

        [HttpPost, JsonExceptionHandlerAttribute]
        public JsonResult FormDataServerTrappedError(HttpPostedFileBase file1, string other)
        {
            throw new Exception("Generic server error");
        }

        #endregion

        private string GetFileData(HttpPostedFileBase file)
        {
            return string.Join(" : ", new object[] { file.ContentLength.ToString() + " bytes", file.ContentType, file.FileName });
        }
    }
}

code/FileUploadSpike/Views/Home/Index.cshtml
@{
    ViewBag.Title = "File Uploader";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ActionLink("Simple upload", "Index", "Upload")
| 
@Html.ActionLink("Form data upload", "FormData", "Upload")

code/FileUploadSpike/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="~/Scripts/jquery-1.8.3.js"></script>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" type="text/css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <h1>@ViewBag.Title</h1>

    @RenderBody()
</body>
</html>

code/FileUploadSpike/Views/Shared/_MultipleUploadForm.cshtml
@using (Html.BeginForm("Index", "Home", FormMethod.Post, new { Id = "uploadForm", Enctype = "multipart/form-data", Class = "form-horizontal" }))
{
    <div class="control-group">
        <label class="control-label">File 1</label>

        <div class="controls">
            <input type="file" name="file1" />
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">File 2</label>

        <div class="controls">
            <input type="file" name="file2" />
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label">Other</label>

        <div class="controls">
            <input type="text" name="other" />
        </div>
    </div>
    
    <div class="control-group">
        <div class="controls">
            <button class="btn btn-success">Upload!</button>
        </div>
    </div>
}

<div id="postData">
    @if (Model != null)
    {
        <p>File 1: @Html.Display("File1Data")</p>
        <p>File 2: @Html.Display("File2Data")</p>
    }
</div>

code/FileUploadSpike/Views/Shared/_UploadForm.cshtml
@using (Html.BeginForm(ViewContext.Controller.ValueProvider.GetValue("action").RawValue.ToString(), ViewContext.Controller.ValueProvider.GetValue("controller").RawValue.ToString(), FormMethod.Post, new { Id = "uploadForm", Enctype = "multipart/form-data", Class = "form-horizontal" }))
{
    <div class="control-group">
        <label class="control-label">File 1</label>

        <div class="controls">
            <input type="file" name="file1" />
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Other</label>

        <div class="controls">
            <input type="text" name="other" />
        </div>
    </div>
    
    <div class="control-group">
        <div class="controls">
            <button class="btn btn-success">Upload!</button>
            <button class="btn btn-danger" type="button" id="cancel">Cancel</button>
        </div>
    </div>
}

<div class="hide">
    <h2>Uploaded files</h2>

    <div id="postData" class="offset1 span10 well">
        @if (Model != null)
        {
            <p>File 1: @Html.Display("File1Data")</p>
        }
    </div>
</div>

code/FileUploadSpike/Views/Upload/FormData.cshtml
@{
    ViewBag.Title = "Form data file upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
    var formViewData = new ViewDataDictionary();
    formViewData.Add("Action", "Upload");
}

@Html.Partial("_UploadForm", (object)Model, formViewData)

<h2>Progress</h2>
<div id="progressConsole">Stand by</div>
<progress id="progress" max="100" value="0"></progress>

<script type="text/javascript">
    var progressConsole = document.getElementById("progressConsole");
    var progress = document.getElementById("progress");

    var form = document.getElementById("uploadForm");
    var cancel = document.getElementById("cancel");
    var uploadOperation = null;

    form.addEventListener("submit", function (formEv) {
        var data = new FormData(form);
        progressConsole.innerHTML = "Uploading files";

        var xhr = new XMLHttpRequest();
        xhr.open("POST", "@Url.Action(ViewContext.Controller.ValueProvider.GetValue("action").RawValue.ToString())", true);
        xhr.upload.onprogress = function (ev) {
            if (ev.lengthComputable) {
                progress.value = Math.round(10000 * ev.loaded / ev.total) / 100;

                if (ev.loaded == ev.total) {
                    progressConsole.innerHTML = "Awaiting response";
                }
            }
        }
        xhr.upload.onload = function (ev) {
            progressConsole.innerHTML = "Awaiting response";
        }
        xhr.onload = function () {
            progressConsole.innerHTML = "Completed";
            uploadOperation = null;

            if (xhr.status == 200) {
                processResponse(JSON.parse(xhr.response));
            } else {
                try {
                    processResponse(JSON.parse(xhr.response));
                } catch (e) {
                    processResponse({ Success: false, Message: $(xhr.response).find("h2").text() });
                }
            }
        }
        xhr.onabort = function () {
            progressConsole.innerHTML = "Canceled";
            processResponse({ Success: false, Message: "Canceled" });
            return false;
        }
        xhr.onerror = function () {
            progressConsole.innerHTML = "Failed";
            processResponse({ Success: false, Message: "Failed" });
        }
        xhr.send(data);

        uploadOperation = xhr;
        formEv.preventDefault();
    });

    cancel.addEventListener("click", function () {
        uploadOperation.abort();
    });

    function processResponse(response) {
        if (response.Sucess) {
            alert(response.Message || "Success!");
        } else {
            alert(response.Message || "Error!");
        }
    }

    window.onbeforeunload = function () {
        if (uploadOperation != null) {
            return "Upload in progress";
        }
    }
</script>

code/FileUploadSpike/Views/Upload/Index.cshtml
@{
    ViewBag.Title = "Simple file upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
    var formViewData = new ViewDataDictionary();
    formViewData.Add("Action", "Upload");
}

@Html.Partial("_UploadForm", (object)Model, formViewData)